module.exports = {
    'USER' : {
        'FIRST_NAME_REQUIRED' : 'First Name is required',
        'FIRST_NAME_LENGTH_VALIDATION' : 'First name must be minimum 2 characters and maximum 20 characters.',
        'LAST_NAME_LENGTH_VALIDATION' : 'Last  name must be minimum 2 characters and maximum 20 characters.',
        'LAST_NAME_REQUIRED' : 'Last Name is required',
        'UPDATE_SUCCESS' : 'Users has been updated successfully',
        'EMAIL_ID_REQUIRED' : 'Email ID is required',
        'PASSWORD_REQUIRED' : 'Password is required',
        'PASSWORD_LENGTH_VALIDATION' : 'Password must be minimum 6 characters and maximum 20 characters.',
        'DOB_REQUIRED' : 'DOB is required',
        'EMAIL_INVALID'  : 'Email ID is not valid.',
        'EMAIL_PASSWORD_REQUIRED' : 'Email id and password is required',
        'LOGIN_SUCCESSFULLY' : 'You have successfully login',
        'INVALID_USER_PASSWORD' : 'Invalid email id and password',
        'EMAIL_NOT_FOUND' : 'Email id not found',
        'EMAIL_AREADY_EXIST' : 'Email ID is already exist.',
        'EMAIL_LENGTH_VALIDATION' : 'Email ID must be minimum 6 characters and maximum 50 characters.',
        'USERNAME_REQUIRED' : 'Username  is already exist.',
        'USERNAME_LENGTH_VALIDATION' : 'Username must be minimum 6 characters and maximum 20 characters.',
        'USER_REGISTER_SUCCESS' : 'Congratulation! You have successfully registered. You will shortly receive a mail for account activation',
        'USER_SUMMARY_FOUND' : 'User summary found',
        'ID_PARAMETER_REQUIRED' : '_id parameter is required',
        'USER_NOT_FOUND' : 'User not found',
        'USER_FOUND' : 'User found',
        'USER_DELETED_SUCCESS' : 'User has been deleted successfully.',
        'FORGOT_PASSWORD_SUCCESS' : 'Peershot have sent an email to your registered Email ID, please  reset your password for login',
        'FORGOT_PASSWORD_TOKEN_NOT_VERIFY' : 'Account is not verified associated with token',
        'FORGOT_PASSWORD_TOKEN_VERIFIED' : 'Account is verified',
        'USER_STATUS_ACTIVE' : 'Úser status is active',
        'USER_STATUS_INACTIVE' : 'User status in inactive',
        'USER_NOT_FOUND' : 'User not found',
        'USER_UPDATE_SUCCESS' : 'User has been updated successfully',
        'COUNTRY_REQUIRED' : 'Country is required',
        'ZIPCODE_REQUIRED' : 'Zip Code is required',
        'OTP_REQUIRED' : 'OTP is required',
        'OTP_NOT_VERIFIED' : 'OTP is not verified',
        'OTP_VERIFIED_SUCCESS' : 'OTP has been verified',
        'OTP_EXPIRED_SUCCESS' : 'OTP has been expired',
        'EMAIL_TEMPLATE_NOT_FOUND': 'Email template not found',
        'RESET_PASSWORD_SUCCESS' : 'Your password has been reset successfully.',
        'USER_INACTIVE_ACCOUNT' : 'Your account is inactive, Contact Peershots Admin to activate your account.',
        'ACCOUNT_ACTIVATION_SUCCESS': 'Your account has been successfully activated, Please login with your registered credential'
    },
    'USER_PHOTO' :{
        'USER_PHOTO_USER_REQUIRED' : 'User is required',
        'USER_PHOTO_LOCATION_TYPE_REQUIRED' : 'Location type is required',
        'USER_PHOTO_LATITUDE_REQUIRED' : 'Latitude is required',
        'USER_PHOTO_LONGITUDE_REQUIRED' : 'Longitude is required',
        'USER_PHOTO_CITY_REQUIRED' : 'City is required',
        'USER_PHOTO_STATE_REQUIRED' : 'State is required',
        'USER_PHOTO_COUNTRY_REQUIRED' : 'Country is required',
        'USER_PHOTO_ZIPCODE_REQUIRED' : 'Zip Code is required',
        'USER_PHOTO_REQUIRED' : 'User photo is required',
        'USER_PHOTO_SAVED_SUCCESSFULLY' : 'User photo has been saved successfully',
        'USER_PHOTO_PRIVATE_LIST_FOUND' : 'User photo private list found',
        'USER_PHOTO_PRIVATE_LIST_NOT_FOUND' : 'User photo private list not found'
    }
};

