module.exports = {
    'USER' : {
        'INSERT_SUCCESS' : 'Users has been added successfully',
        'UPDATE_SUCCESS' : 'Users has been updated successfully',
        'INVALID_EMAIL'  : 'Email id is not valid',
        'EMAIL_PASSWORD_REQUIRED' : 'Email id and password is required',
        'LOGIN_SUCCESSFULLY' : 'You have successfully login',
        'INVALID_USER_PASSWORD' : 'Invalid email id and password',
        'EMAIL_NOT_FOUND' : 'Email id not found',
        'EMAIL_AREADY_EXIST' : 'Email id is already exist',
        'USER_SUMMARY_FOUND' : 'User summary found',
        'ID_PARAMETER_REQUIRED' : '_id parameter is required',
        'USER_NOT_FOUND' : 'User not found',
        'USER_FOUND' : 'User found',
        'USER_DELETED_SUCCESS' : 'User has been deleted successfully.',
        'FORGOT_PASSWORD_SUCCESS' : 'Peershot have sent an email to your registered Email ID, please  reset your password for login',
        'FORGOT_PASSWORD_TOKEN_NOT_VERIFY' : 'Account is not verified associated with token',
        'FORGOT_PASSWORD_TOKEN_VERIFIED' : 'Account is verified',
        'RESET_PASSWORD_SUCCESS' : 'Your password has been reset successfully.',
        'USER_STATUS_ACTIVE' : 'Úser status is active',
        'USER_STATUS_INACTIVE' : 'Status has been changed successfully',
        'USER_NOT_FOUND' : 'User not found',
        'USER_UPDATE_SUCCESS' : 'User has been updated successfully',
        'CHANGE_PASSWORD_SUCCESS':'Password has been changed successfully',
        'APP_INSERT_SUCCESS':'User has been registered successfully',
        'USERNAME_ALREADY_EXIST':'Username is already exist',
        'ALREADY_ACCOUNT_ACTIVE':'Your account has been already activated',
        "APP_RESEND_EMAIL":'Resend Activation Email has been sent successfully'
    },
    'ROLES' : {
        'ROLE_SUMMARY_FOUND' : 'Role summary found',
        'INSERT_SUCCESS' : 'Role has been added successfully',
        'UPDATE_SUCCESS' : 'Role has been updated successfully',        
        'ROLE_NAME_REQUIRED' : 'Role name is required',
        'ROLE_DESCRIPTION_REQUIRED' : 'Role description is required',        
        'ROLE_NAME_ALREADY_EXIST' : 'Role name is already exist',        
        'ID_PARAMETER_REQUIRED' : '_id parameter is required',       
        'ROLE_NOT_FOUND' : 'Role not found',
        'ROLE_FOUND' : 'Role found',
        'ROLE_DELETED_SUCCESS' : 'Role has been deleted successfully.',
        'UPDATE_STATUS' :'Status has been changed successfully',
        'UPDATE_PERMISSION_STATUS':'Permission has been updated successfully',
    },
      'CMS' : {
        'INSERT_SUCCESS' : 'CMS has been added successfully',
        'UPDATE_SUCCESS' : 'CMS has been updated successfully',        
        'PAGE_NAME_REQUIRED' : 'CMS page name is required',
        'PAGE_CONTENT_REQUIRED' : 'CMS page content is required',        
        'PAGE_NAME_ALREADY_EXIST' : 'CMS page name is already exist',        
        'ID_PARAMETER_REQUIRED' : '_id parameter is required',
        'CMS_SUMMARY_FOUND' : 'CMS summary found',
        'CMS_NOT_FOUND' : 'Cms not found',
        'CMS_FOUND' : 'Cms found',
        'CMS_DELETED_SUCCESS' : 'Cms has been deleted successfully.',
        'UPDATE_STATUS' :'Status has been changed successfully',        
    },
    'EMAIL_TEMPLATE' : {
      'INSERT_SUCCESS' : 'Email template has been added successfully',
      'UPDATE_SUCCESS' : 'Email template has been updated successfully',        
      'EMAIL_TITLE_REQUIRED' : 'Email template title is required',
      'EMAIL_CONTENT_REQUIRED' : 'Email template content is required',        
      'EMAIL_TITLE_ALREADY_EXIST' : 'Email template title is already exist',        
      'ID_PARAMETER_REQUIRED' : '_id parameter is required',
      'EMAIL_TEMPLATE_SUMMARY_FOUND' : 'Email template summary found',
      'EMAIL_TEMPLATE_NOT_FOUND' : 'Email template not found',
      'EMAIL_TEMPLATE_FOUND' : 'Email template found',
      'EMAIL_TEMPLATE_DELETED_SUCCESS' : 'Email template has been deleted successfully.',
      'UPDATE_STATUS' :'Status has been changed successfully',        
  },
  'GLOBAL_SETTING' : {
    'UPDATE_SUCCESS' : 'Global setting has been updated successfully',
    'ID_PARAMETER_REQUIRED' : '_id parameter is required',
    'GLOBAL_SETTING_FOUND' : 'Global setting found',
    'GLOBAL_SETTING_NOT_FOUND' : 'Global setting not found',
              
    },
    'MANAGE_PRICE' : {
      'INSERT_SUCCESS' : 'Price has been added successfully',
      'UPDATE_SUCCESS' : 'Price has been updated successfully',        
      'PRICE_REQUIRED' : 'Price is required',
      'PEER_POINTS_REQUIRED' : 'Peer points is required',        
      'PRICE_ALREADY_EXIST' : 'Price is already exist',        
      'ID_PARAMETER_REQUIRED' : '_id parameter is required',
      'PRICE_SUMMARY_FOUND' : 'Price summary found',
      'PRICE_NOT_FOUND' : 'Price not found',
      'PRICE_FOUND' : 'Price found',
      'PRICE_DELETED_SUCCESS' : 'Price has been deleted successfully.',
      'UPDATE_STATUS' :'Status has been changed successfully',        
    },

    'PRODUCT' : {
        'INSERT_SUCCESS' : 'Product has been added successfully',
        'UPDATE_SUCCESS' : 'Product has been updated successfully',        
        'PRODUCT_NAME_REQUIRED' : 'Product name is required',               
        'PRODUCT_NAME_ALREADY_EXIST' : 'Product name is already exist',        
        'ID_PARAMETER_REQUIRED' : '_id parameter is required',
        'PRODUCT_SUMMARY_FOUND' : 'Product summary found',
        'PRODUCT_NOT_FOUND' : 'Product not found',
        'PRODUCT_FOUND' : 'Product found',
        'PRODUCT_DELETED_SUCCESS' : 'Product has been deleted successfully.',
        'UPDATE_STATUS' :'Status has been changed successfully',        
    },
    'PHOTO' : {
        'PHOTO_LIST_FOUND_SUCCESSFULLY' : 'Photo list found successfully',
        'PHOTO_LIST_NOT_FOUND' : 'Photo list not found',
        'PHOTO_NOT_FOUND' : 'Photo is not found',
        'PHOTO_STATUS_ACTIVE' : 'Photo status is active',
        'PHOTO_STATUS_INACTIVE' : 'Photo statis is inactive',
        'PHOTO_DELETED_SUCCESS' : 'Photo has been deleted'
    },
    'REDEMPTION_REQUEST' : {
        'REDEMPTION_REQUEST_REQUIRED' : 'Redemption request is required',
        'ID_PARAMETER_REQUIRED' : '_id parameter is required',
        'REDEMPTION_REQUEST_SUMMARY_FOUND' : 'Redemption request summary found',
        'REDEMPTION_REQUEST_NOT_FOUND' : 'Redemption request not found',
        'REDEMPTION_REQUEST_FOUND' : 'Redemption request found',        
        'UPDATE_STATUS' :'Status has been changed successfully',        
    },
    "CONTACT_ADMIN" : {
        'CONTACT_ADMIN_LIST_FOUND' : 'Contact admin list found',
        'CONTACT_ADMIN_LIST_NOT_FOUND' : 'Contact admin list not found',
        'CONTACT_ADMIN_RECORD_DELETED' : 'Contact admin record has been deleted successfully'
    },
    "FEEDBACK" : {
        'FEEDBACK_LIST_FOUND' : 'Feedback list found',
        'FEEDBACK_LIST_NOT_FOUND' : 'Feedback list not found',
        'FEEDBACK_RECORD_DELETE' : 'Feedback record has been deleted successfully'
    },
    "LEADERBOARD" : {
        "LEADERBOARD_LIST_FOUND" : 'Leaderboars list is found',
        "LEADERBOARD_NOT_FOUND" : 'Leaderboard is not found'
    }
};

